name: cfb_store
description: A lightweight and flexible key-value storage package for Dart applications. CFB Store provides simple data persistence with support for primitive values, lists, maps, and custom event notifications for store operations.
version: 0.5.1
repository: https://github.com/ThanCoder/cfb_store_dart.git

environment:
  sdk: ^3.12.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
